### ISSUE TITLE
[제안] Windows Sandbox를 이용한 가상머신 대신 Sandboxie 사용

### ISSUE THREAD

**Issue by 7k5x** [dotnetdev-kr/TableCloth#14]
WIndows Sandbox를 사용하면 Hyper-V를 켜야 하는 것과 시스템 리소스 사용량을 많이 켜야 한다는 문제점 때문에 별로 많이 사용하지는 않을 거 같네요
WSL 쓰는 분들은 Hyper-V 는 별로 신경 안 쓰겠지만 윈도우 샌드박스로 가상머신을 돌리면 리소스 사용량 때문에 시스템이 엄청 느려지게 될거 같아서 차라리 가상머신 없이 샌드박스 환경을 제공해주는 Sandboxie를 쓰는게 어떨까 싶어요
오픈소스로 풀린 소프트웨어이기도 하고

**Comment by rkttu** [comment]
제안 감사드립니다. Sandboxie의 모델이 흥미롭기는 하지만, 몇 가지 걸림돌이 있습니다.
- Sandboxie Github 리포지터리 (https://github.com/sandboxie/)에 아직 정식으로 릴리스된 내역이 보이지 않습니다. 또한 이슈 내역들이 제대로 관리되지 않고 있고, 프로젝트가 활성화되어있는지 여부가 잘 보이지 않습니다.
- 동작 특성 상 디바이스 드라이버를 빌드하고 배포해야 하는데, 일반 대중으로 배포하기 위해서는 디바이스 드라이버에 EV 서명을 넣어야 할 것 같습니다. 저는 기업 개발자가 아닌 개인 개발자이며, EV 인증서를 구매할 자격을 갖추고 있지 않습니다.

덧. 말씀하신대로 Windows Sandbox는 가상화 기술을 필요로 합니다. 하지만 Hyper-V로 별도 VM을 만드는 것보다는 여러모로 간소화된 기술을 사용합니다. 내부적으로는 유틸리티 VM 모델을 사용하며, 호스트와 상호 작용하면서 동적으로 VM의 메모리를 조절하도록 되어있어, WSL의 사례처럼 메모리가 제 때 리클레임되지 않아 누수가 발생하는 상황이 아니라면 이론상 "무겁지 않습니다." 그럼에도 불구하고, 패러렐즈 같으 이미 가상화 상태로 윈도우를 실행 중인 곳에서는 윈도우 샌드박스가 비정상적으로 느릴 여지가 있으며, 그럴 경우를 위한 얼터너티브로 Sandboxie 같은 도구의 지원 가능성은 항상 염두에 두도록 하겠습니다.
