### ISSUE TITLE
창 크기가 올바르지 않게 나타나는 현상

### ISSUE THREAD

**Issue by level120** [dotnetdev-kr/TableCloth#3]
![image](https://user-images.githubusercontent.com/10791961/126300695-2aceee68-39a2-4066-9240-6e86ceee097c.png)

Windows 11 Pro 21H2(22000.71)
3840 x 2160
150%

**Comment by rkttu** [comment]
커밋 168ea94 에서 이 문제를 수정해보았습니다. 해당 커밋 이후 빌드에서 어떻게 표시되는지 봐주시면 감사하겠습니다.

**Comment by level120** [comment]
![image](https://user-images.githubusercontent.com/10791961/126467783-ed9915a6-b0dc-4c65-bed0-82703d5ac6f2.png)

이렇게 나오는데 의도하신 화면이 맞나요?
일단 뱅킹쪽 스크롤 바가 나타나지 않아 어색한게 좀 있습니다.

**Comment by rkttu** [comment]
Windows 11에서는 스크롤바 컨트롤에 대한 디자인에 변경된 부분이 있는 것 같습니다. 동일한 150% 확대 비율로 Windows 10에서 확인해 볼때에는 그림처럼 표시가 됩니다. 이 부분은 Windows Forms와 Windows OS의 상호 작용에 대한 부분으로 따로 리포팅이 이루어져야 할 것 같습니다.

![image](https://user-images.githubusercontent.com/1297346/126472704-64ea7fc4-302f-4b93-b276-3e49f02de44a.png)

다만 Windows Forms를 이용해서 레이아웃을 만들다보니 확실히 알게 된 부분이 있는데, .NET 5 이후로도 Windows Forms는 WPF에 비해 여전히 High DPI 지원에 취약한 부분이 많은 것 같습니다. 하여, WPF로 레이아웃을 재설계하는 것을 검토하고 있습니다.
